wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.20.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750336486
    t:
      1:
      - 1
      - 41
      - 43
      - 49
      - 63
      - 79
      3:
      - 4
      - 13
      - 15
      - 16
      - 42
      - 55
      4: 3.11.11
      5: 0.20.1
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 4
max_iterations:
  desc: null
  value: 80000
contact_state_modality:
  desc: null
  value: mask+rgb+depth+fusion
num_classes:
  desc: null
  value: 20
